# Generated by Django 4.2.6 on 2023-10-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse',
            old_name='Channel',
            new_name='pulse_output',
        ),
    ]
