# Generated by Django 4.2.6 on 2023-10-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_channel_pulse_pulse_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='pulse_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.pulseoutput'),
        ),
    ]
